
app:
  prefix: /mnt/metaverse/scene
  startPoint: 22 #141 #29
  appId: "0000000008" #"0000000007" #"0000000003"

log:
  logFolder: /var/log/metaverse

queueConfig:
  move: 60
  rotate: 2
  joystick: 5

http:
  host: '0.0.0.0'
  port: 6688


grpc:
  url: '192.168.0.200:3000'

# redis:
#   port: 26379
#   host: '221.4.210.172' #远程调试需要设置bindip 为0.0.0.0 并且设置密码
#   password: '' # 非远程不需要密码
#   decode_responses: true
#   db: 9

redis:
  port: 6379
  host: '192.168.0.47' #远程调试需要设置bindip 为0.0.0.0 并且设置密码
  password: '' # 非远程不需要密码
  decode_responses: true
  db: 9

queueRedis:
  port: 6379
  host: 'localhost' #远程调试需要设置bindip 为0.0.0.0 并且设置密码
  password: 'redis9394' # 非远程不需要密码
  decode_responses: true
  db: 14

stun:
  #server: ['turn:4dage:4dage168@47.107.125.202:4478', 'stun:47.107.125.202:3478']
  server: ['stun:175.178.12.158:3478','stun:106.55.177.178:3478']
  portRangeBegin: 49152
  portRangeEnd: 65535

server:
  private_ip: 172.18.197.114
  public_ip: 120.24.252.95

  
# PRIVATE_IP=172.18.197.114
# PUBLIC_IP=120.24.252.95
# STUNS_SEVER="stun:172.18.156.41:3478,stun:120.24.252.95:3478"
# GRPC_URL="192.168.0.48:3000"
# REDIS_URL="redis://:192.168.0.47:6379/9"
